In [3]:
import numpy as np
my_arr = np.arange(1000000)
my_list = list(range(1000000))

In [8]:
%time for _ in range(10): my_arr2 = my_arr *2

Wall time: 33.9 ms


In [9]:
%time for _ in range(10): my_list2 = [x * 2 for x in my_list]

Wall time: 1.11 s


In [11]:
data = np.random.randn(2,3)
print(data)

[[ 0.16262295 -0.03051139 -0.77370815]
 [ 0.48472273  0.4935392   0.9522961 ]]


# 数学运算

In [13]:
# 所有元素*10
print('data * 10: \n',data *10)

data * 10: 
 [[ 1.62622953 -0.3051139  -7.73708147]
 [ 4.84722733  4.93539203  9.52296104]]


In [15]:
#每个元素与自己相加
print('data + data: \n',data +data)

data + data: 
 [[ 0.32524591 -0.06102278 -1.54741629]
 [ 0.96944547  0.98707841  1.90459221]]


In [17]:
# 每个数组都有一个shape（一个表示各维度大小的元组）和一个dtype（一个用于说明数组数据类型的对象）
print(data.shape)
print(data.dtype)

(2, 3)
float64


# 创建ndarray

In [18]:
# 创建数组最简单的办法就是使用array函数
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
print(arr1)

[6.  7.5 8.  0.  1. ]


In [19]:
# 嵌套序列（比如由一组等长列表组成的列表）将会被转换为一个多维数组
data2 = [[1,2,3,4],[5,6,7,8]]
arr2 = np.array(data2)
print(arr2)

[[1 2 3 4]
 [5 6 7 8]]


In [21]:
# 因为data2是列表的列表，NumPy数组arr2的两个维度的shape是从data2引入的。可以用属性ndim和shape验证
print(arr2.ndim)
print(arr2.shape)

2
(2, 4)


In [22]:
# np.array会尝试为新建的这个数组推断出一个较为合适的数据类型。数据类型保存在一个特殊的dtype对象中
print(arr1.dtype)
print(arr2.dtype)

float64
int32


In [27]:
'''
除np.array之外，
zeros和ones分别可以创建指定长度或形状的全0或全1数组。
empty可以创建一个没有任何具体值的数组。要用这些方法创建多维数组，只需传入一个表示形状的元组即可
'''
print(np.zeros(10))
print(np.zeros((3,6)))
print(np.empty((2,3,2)))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
[[[6.23042070e-307 1.42417221e-306]
  [1.37961641e-306 6.23039354e-307]
  [1.06811422e-306 1.27946076e-307]]

 [[1.42418987e-306 1.69122046e-306]
  [1.86921958e-306 6.89804133e-307]
  [1.11261162e-306 8.34443015e-308]]]


In [29]:
# arange是Python内置函数range的数组版
print(np.arange(10))
print(range(10))

[0 1 2 3 4 5 6 7 8 9]
range(0, 10)


In [33]:
# 可以通过ndarray的astype方法明确地将一个数组从一个dtype转换成另一个dtype
arr = np.array([1,2,3,4,5])
print(arr.dtype)
float_arr = arr.astype(np.float64)
print(float_arr.dtype)


int32
float64


In [37]:
# 整数被转换成了浮点数。如果将浮点数转换成整数，则小数部分将会被截取删除：

arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])
print(arr)
print(arr.astype(np.int32))

[ 3.7 -1.2 -2.6  0.5 12.9 10.1]
[ 3 -1 -2  0 12 10]


In [39]:
# 如果某字符串数组表示的全是数字，也可以用astype将其转换为数值形式
numeric_strings = np.array(['1.25', '-9.6', '42'],dtype=np.string_)
print(numeric_strings.astype(float))

[ 1.25 -9.6  42.  ]


In [41]:
# 用简洁的类型代码来表示dtype
empty_uint32 = np.empty(8,dtype='u4')
print(empty_uint32)
print(empty_uint32.dtype)

[         0 1075314688          0 1075707904          0 1075838976
          0 1072693248]
uint32


In [42]:
# NumPy数组的运算
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
print(arr)
print(arr * arr)
print(arr - arr)

[[1. 2. 3.]
 [4. 5. 6.]]
[[ 1.  4.  9.]
 [16. 25. 36.]]
[[0. 0. 0.]
 [0. 0. 0.]]


In [44]:
# 数组与标量的算术运算会将标量值传播到各个元素
print(1 / arr)
print(arr **0.5)

[[1.         0.5        0.33333333]
 [0.25       0.2        0.16666667]]
[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]]


In [45]:
# 大小相同的数组之间的比较会生成布尔值数组
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])
print(arr2)
print(arr2 > arr)

[[ 0.  4.  1.]
 [ 7.  2. 12.]]
[[False  True False]
 [ True False  True]]


In [ ]:
'''
数组的广播
如果两个数组的维数不相同，则元素到元素的操作是不可能的。 然而，在 NumPy 中仍然可以对形状不相似的数组进行操作，因为它拥有广播功能。 较小的数组会广播到较大数组的大小，以便使它们的形状可兼容。

如果满足以下规则，可以进行广播：

ndim较小的数组会在前面追加一个长度为 1 的维度。
输出数组的每个维度的大小是输入数组该维度大小的最大值。
如果输入在每个维度中的大小与输出大小匹配，或其值正好为 1，则可以在计算中使用该输入。
如果输入的某个维度大小为 1，则该维度中的第一个数据元素将用于该维度的所有计算。
如果上述规则产生有效结果，并且满足以下条件之一，那么数组被称为可广播的。

数组拥有相同形状。
数组拥有相同的维数，每个维度拥有相同长度，或者长度为 1。
数组拥有极少的维度，可以在其前面追加长度为 1 的维度，使上述条件成立。
'''

In [49]:
# 广播的示例
a = np.array([[0.0,0.0,0.0],[10.0,10.0,10.0],[20.0,20.0,20.0],[30.0,30.0,30.0]])
b = np.array([1.0,2.0,3.0])
print ('第一个数组：')  
print (a) 
print (a.shape) 
print ('\n第二个数组：')  
print (b) 
print (b.shape) 
print ('\n第一个数组加第二个数组：')  
print (a + b)

第一个数组：
[[ 0.  0.  0.]
 [10. 10. 10.]
 [20. 20. 20.]
 [30. 30. 30.]]
(4, 3)

第二个数组：
[1. 2. 3.]
(3,)

第一个数组加第二个数组：
[[ 1.  2.  3.]
 [11. 12. 13.]
 [21. 22. 23.]
 [31. 32. 33.]]


# 基本的索引和切片

In [52]:
arr = np.arange(10)
print(arr)
print(arr[5])
print(arr[5:8])
arr[5:8] = 12
print(arr)
'''
当你将一个标量值赋值给一个切片时（如arr[5:8]=12），
该值会自动传播到整个选区。跟列表最重要的区别在于，数组切片是原始数组的视图。这意味着数据不会被复制，视图上的任何修改都会直接反映到源数组上
'''

[0 1 2 3 4 5 6 7 8 9]
5
[5 6 7]
[ 0  1  2  3  4 12 12 12  8  9]


In [53]:
arr_slice = arr[5:8]
print(arr_slice)

[12 12 12]


In [54]:
arr_slice[1] = 123456
print(arr)
# 当我修稿arr_slice中的值，变动也会体现在原始数组arr中

[     0      1      2      3      4     12 123456     12      8      9]


In [55]:
# 切片[ : ]会给数组中的所有值赋值
arr_slice[:] = 64
print(arr)

[ 0  1  2  3  4 64 64 64  8  9]


In [56]:
# 在一个二维数组中，各索引位置上的元素不再是标量而是一维数组
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2d[2])

[7 8 9]


In [58]:
# 可以对各个元素进行递归访问，但这样需要做的事情有点多。你可以传入一个以逗号隔开的索引列表来选取单个元素。也就是说，下面两种方式是等价的
print(arr2d[0][2])
print(arr2d[0,2])

3
3


In [59]:
# 在多维数组中，如果省略了后面的索引，则返回对象会是一个维度低一点的ndarray（它含有高一级维度上的所有数据）
arr3d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr3d)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [66]:
print(arr3d[0][0])
print(arr3d[0])
print(arr3d[1])

[1 2 3]
[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [67]:
#将arr3d[0]的数据进行备份
old_values = arr3d[0].copy()
arr3d[0] = 42
print(arr3d)
print('===========分割线============')
arr3d[0] = old_values
print(arr3d)

[[[42 42 42]
  [42 42 42]]

 [[ 7  8  9]
  [10 11 12]]]
===========分割线============
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [69]:
print(arr3d[1,0])
print('===========分割线============')
x = arr3d[1]
print(x)
print(x[0])

[7 8 9]
===========分割线============
[[ 7  8  9]
 [10 11 12]]
[7 8 9]


In [70]:
# 切片索引

print(arr)
print(arr[1:6])

[ 0  1  2  3  4 64 64 64  8  9]
[ 1  2  3  4 64]


In [72]:
print(arr2d)
print('===========分割线============')
print(arr2d[:2])
print(arr2d[1:2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
===========分割线============
[[1 2 3]
 [4 5 6]]
[[4 5 6]]


In [73]:
'''
可以看出，它是沿着第0轴（即第一个轴）切片的。也就是说，切片是沿着一个轴向选取元素的。表达式arr2d[:2]可以被认为是“选取arr2d的前两行”。
你可以一次传入多个切片，就像传入多个索引那样
'''
print(arr2d[:2,1:])
# 像这样进行切片时，只能得到相同维数的数组视图。通过将整数索引和切片混合，可以得到低维度的切片

[[2 3]
 [5 6]]


In [74]:
# 我可以选取第二行的前两列
print(arr2d[1,:2])

[4 5]


In [75]:
# 还可以选择第三列的前两行
print(arr2d[:2,2])

[3 6]


In [76]:
print(arr2d[:,:1])
# 对切片表达式的赋值操作也会被扩散到整个选区

[[1]
 [4]
 [7]]


# 布尔型索引

In [77]:

# 使用numpy.random中的randn函数生成一些正态分布的随机数据
names  = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7,4)
print(names)
print(data)

['Bob' 'Joe' 'Will' 'Bob' 'Will' 'Joe' 'Joe']
[[-1.53020711 -1.16544357  0.43972525 -0.83016591]
 [-0.74601487 -0.53537919  1.06682344 -0.64511843]
 [-1.25930533 -0.81838881 -0.87597403  0.08405453]
 [-0.86763855 -1.95116546  1.2608911  -0.30190242]
 [-0.78570627 -0.67785675 -1.18340596  0.53864007]
 [ 3.38654762 -0.98492737  0.726546   -0.68898722]
 [-0.52710439  0.1427326  -0.09873204 -0.19288784]]


In [78]:
'''
假设每个名字都对应data数组中的一行，而我们想要选出对应于名字"Bob"的所有行。
跟算术运算一样，数组的比较运算（如==）也是矢量化的。因此，对names和字符串"Bob"的比较运算将会产生一个布尔型数组
'''
print(names =='Bob')

[ True False False  True False False False]


In [79]:
# 这个布尔型数组可用于数组索引
print(data[names =='Bob'])

[[-1.53020711 -1.16544357  0.43972525 -0.83016591]
 [-0.86763855 -1.95116546  1.2608911  -0.30190242]]


In [82]:
# 布尔型数组的长度必须跟被索引的轴长度一致。此外，还可以将布尔型数组跟切片、整数（或整数序列，稍后将对此进行详细讲解）混合使用
print(data[names =='Bob',2:])
print('===========分割线============')
print(data[names =='Bob',3])

[[ 0.43972525 -0.83016591]
 [ 1.2608911  -0.30190242]]
===========分割线============
[-0.83016591 -0.30190242]


In [84]:
# 要选择除"Bob"以外的其他值，既可以使用不等于符号（!=），也可以通过~对条件进行否定
print(data[names != 'Bob'])
print(data[~(names == 'Bob')])


[[-0.74601487 -0.53537919  1.06682344 -0.64511843]
 [-1.25930533 -0.81838881 -0.87597403  0.08405453]
 [-0.78570627 -0.67785675 -1.18340596  0.53864007]
 [ 3.38654762 -0.98492737  0.726546   -0.68898722]
 [-0.52710439  0.1427326  -0.09873204 -0.19288784]]
[[-0.74601487 -0.53537919  1.06682344 -0.64511843]
 [-1.25930533 -0.81838881 -0.87597403  0.08405453]
 [-0.78570627 -0.67785675 -1.18340596  0.53864007]
 [ 3.38654762 -0.98492737  0.726546   -0.68898722]
 [-0.52710439  0.1427326  -0.09873204 -0.19288784]]


In [85]:
# ~操作符用来反转条件很好用
cond = names =='Bob'
print(data[~cond])

[[-0.74601487 -0.53537919  1.06682344 -0.64511843]
 [-1.25930533 -0.81838881 -0.87597403  0.08405453]
 [-0.78570627 -0.67785675 -1.18340596  0.53864007]
 [ 3.38654762 -0.98492737  0.726546   -0.68898722]
 [-0.52710439  0.1427326  -0.09873204 -0.19288784]]


In [87]:
# 选取这三个名字中的两个需要组合应用多个布尔条件，使用&（和）、|（或）之类的布尔算术运算符即可

mask = (names =='Bob') | (names =='will')
print(mask)
print(data[mask])
# 通过布尔型索引选取数组中的数据，将总是创建数据的副本，即使返回一模一样的数组也是如此

[ True False False  True False False False]
[[-1.53020711 -1.16544357  0.43972525 -0.83016591]
 [-0.86763855 -1.95116546  1.2608911  -0.30190242]]


In [88]:
# 通过布尔型数组设置值是一种经常用到的手段。为了将data中的所有负值都设置为0，我们只需
data[data < 0] = 0
print(data)

[[0.         0.         0.43972525 0.        ]
 [0.         0.         1.06682344 0.        ]
 [0.         0.         0.         0.08405453]
 [0.         0.         1.2608911  0.        ]
 [0.         0.         0.         0.53864007]
 [3.38654762 0.         0.726546   0.        ]
 [0.         0.1427326  0.         0.        ]]


In [89]:
# 通过一维布尔数组设置整行或列的值也很简单
data[names !='Joe'] = 7
print(data)

[[7.         7.         7.         7.        ]
 [0.         0.         1.06682344 0.        ]
 [7.         7.         7.         7.        ]
 [7.         7.         7.         7.        ]
 [7.         7.         7.         7.        ]
 [3.38654762 0.         0.726546   0.        ]
 [0.         0.1427326  0.         0.        ]]


# 花式索引

In [97]:
# 花式索引（rFancy indexing）是一个NumPy术语，它指的是利用整数数组进行索引。
arr = np.empty((8,4))
for i in range(8):
    arr[i] = i
print(arr)

[[0. 0. 0. 0.]
 [1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [3. 3. 3. 3.]
 [4. 4. 4. 4.]
 [5. 5. 5. 5.]
 [6. 6. 6. 6.]
 [7. 7. 7. 7.]]


In [98]:
# 为了以特定顺序选取行子集，只需传入一个用于指定顺序的整数列表或ndarray即可
print(arr[[4,3,0,6]])

[[4. 4. 4. 4.]
 [3. 3. 3. 3.]
 [0. 0. 0. 0.]
 [6. 6. 6. 6.]]


In [99]:
# 使用负数索引将会从末尾开始选取行
print(arr[[-7,-5,-1]])

[[1. 1. 1. 1.]
 [3. 3. 3. 3.]
 [7. 7. 7. 7.]]


In [101]:
arr = np.arange(32).reshape((8,4))
print(arr)
print(arr[[1,5,7,2],[0,3,1,2]])
# 最终选出的是元素(1,0)、(5,3)、(7,1)和(2,2) 无论数组是多少维的，花式索引总是一维的

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]
[ 4 23 29 10]


In [103]:
# 记住，花式索引跟切片不一样，它总是将数据复制到新数组中
print(arr[[1,3,7,2]][:,[0,3,1,2]])


[[ 4  7  5  6]
 [12 15 13 14]
 [28 31 29 30]
 [ 8 11  9 10]]


# 数组转置和轴对换

In [104]:
# 转置是重塑的一种特殊形式，它返回的是源数据的视图（不会进行任何复制操作）。数组不仅有transpose方法，还有一个特殊的T属性
arr = np.arange(15).reshape((3,5))
print(arr)
print(arr.T)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


In [106]:
# 在进行矩阵计算时，经常需要用到该操作，比如利用np.dot计算矩阵内积
arr = np.random.randn(6,3)
print(arr)
print(np.dot(arr.T,arr))

[[-0.04482362 -0.14886476 -0.45386796]
 [-1.09575105  0.10298167  0.21063826]
 [ 0.72509345 -1.94062038  0.69397611]
 [-0.34692531 -0.2968478  -1.48837084]
 [-0.26380565 -0.76818896  1.55805606]
 [-0.06405768  1.17301512 -0.38294925]]
[[ 1.92249401 -1.28280475  0.4225948 ]
 [-1.28280475  5.85297078 -2.46175448]
 [ 0.4225948  -2.46175448  5.521404  ]]


In [107]:
# 对于高维数组，transpose需要得到一个由轴编号组成的元组才能对这些轴进行转置（比较费脑子）
arr = np.arange(16).reshape((2,2,4))
print(arr)
print('==========分割线==============')
print(arr.transpose((1,0,2)))
# 这里，第一个轴被换成了第二个，第二个轴被换成了第一个，最后一个轴不变

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]]
==========分割线==============
[[[ 0  1  2  3]
  [ 8  9 10 11]]

 [[ 4  5  6  7]
  [12 13 14 15]]]


In [108]:
# 简单的转置可以使用.T，它其实就是进行轴对换而已。ndarray还有一个swapaxes方法，它需要接受一对轴编号
print(arr)
print('==========分割线==============')
print(arr.swapaxes(1,2))
# swapaxes也是返回源数据的视图（不会进行任何复制操作）

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]]
==========分割线==============
[[[ 0  4]
  [ 1  5]
  [ 2  6]
  [ 3  7]]

 [[ 8 12]
  [ 9 13]
  [10 14]
  [11 15]]]


# 通用函数：快速的元素级数组函数

In [111]:
'''
通用函数（即ufunc）是一种对ndarray中的数据执行元素级运算的函数。
你可以将其看做简单函数（接受一个或多个标量值，并产生一个或多个标量值）的矢量化包装器
'''
# 许多ufunc都是简单的元素级变体，如sqrt和exp
arr = np.arange(10)
print(arr)
print(np.sqrt(arr))
print('-' *50)
print(np.exp(arr))

[0 1 2 3 4 5 6 7 8 9]
[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ]
--------------------------------------------------
[1.00000000e+00 2.71828183e+00 7.38905610e+00 2.00855369e+01
 5.45981500e+01 1.48413159e+02 4.03428793e+02 1.09663316e+03
 2.98095799e+03 8.10308393e+03]


In [112]:
'''
这些都是一元（unary）ufunc。另外一些（如add或maximum）
接受2个数组（因此也叫二元（binary）ufunc），并返回一个结果数组
'''
x = np.random.randn(8)
y = np.random.randn(8)

print(x)
print(y)
print('-'*80)
print(np.maximum(x,y))

[ 0.36557763 -0.1906969  -1.19811511  0.55521106 -0.0780733   0.2145469
  0.78105192 -0.15315845]
[-0.93367438 -0.11387392 -0.20217292 -0.68836326  1.12478367  1.63629519
  0.52362167  0.90502397]
--------------------------------------------------------------------------------
[ 0.36557763 -0.11387392 -0.20217292  0.55521106  1.12478367  1.63629519
  0.78105192  0.90502397]


In [114]:
# 虽然并不常见，但有些ufunc的确可以返回多个数组。modf就是一个例子，它是Python内置函数divmod的矢量化版本，它会返回浮点数数组的小数和整数部分
arr = np.random.randn(7) *5
print(arr)
remainder, whole_part = np.modf(arr)
print(remainder)
print(whole_part)

[ 2.84731833  5.92724302  0.71073876  1.54584911 -6.1538011   4.93273441
 -0.77150126]
[ 0.84731833  0.92724302  0.71073876  0.54584911 -0.1538011   0.93273441
 -0.77150126]
[ 2.  5.  0.  1. -6.  4. -0.]


In [115]:
# Ufuncs可以接受一个out可选参数，这样就能在数组原地进行操作
print(arr)
print(np.sqrt(arr))
print(np.sqrt(arr,arr))
print(arr)

[ 2.84731833  5.92724302  0.71073876  1.54584911 -6.1538011   4.93273441
 -0.77150126]
[1.68739987 2.43459299 0.84305324 1.2433218         nan 2.220976
        nan]
[1.68739987 2.43459299 0.84305324 1.2433218         nan 2.220976
        nan]
[1.68739987 2.43459299 0.84305324 1.2433218         nan 2.220976
        nan]


d:\python37\lib\site-packages\ipykernel_launcher.py:3: RuntimeWarning: invalid value encountered in sqrt
  This is separate from the ipykernel package so we can avoid doing imports until
d:\python37\lib\site-packages\ipykernel_launcher.py:4: RuntimeWarning: invalid value encountered in sqrt
  after removing the cwd from sys.path.
